# Generated by Django 6.0.4 on 2026-04-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopbanner",
            name="discount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shopbanner",
            name="template",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="shopbanner",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="banners/"),
        ),
    ]
