# Generated by Django 6.0.4 on 2026-04-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_shopbanner_discount_shopbanner_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopbanner",
            name="template",
            field=models.CharField(
                blank=True,
                choices=[("red", "Red"), ("green", "Green"), ("dark", "Dark")],
                max_length=20,
            ),
        ),
    ]
