# Generated by Django 6.0.4 on 2026-04-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_shopbanner_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopbanner",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
