# Generated by Django 6.0.4 on 2026-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_featuredbanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredbanner",
            name="background_color",
            field=models.CharField(default="#2F5D50", max_length=20),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="banner_type",
            field=models.CharField(
                choices=[("image", "Image"), ("text", "Text")],
                default="image",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="small_text",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="subtitle",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="featuredbanner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="featured_banners/"
            ),
        ),
    ]
