# Generated by Django 6.0.4 on 2026-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_featuredbanner_background_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopbanner",
            name="title",
        ),
        migrations.AddField(
            model_name="shopbanner",
            name="banner_type",
            field=models.CharField(
                choices=[("image", "Image"), ("text", "Text")],
                default="image",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="shopbanner",
            name="template",
            field=models.CharField(default="green", max_length=20),
        ),
    ]
