# Generated by Django 6.0.4 on 2026-04-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_shopbanner_title_shopbanner_banner_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopbanner",
            name="subtitle",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="shopbanner",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
