# Generated by Django 6.0.4 on 2026-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_profile_profile_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.CharField(default="male_1", max_length=20),
        ),
    ]
