# Generated by Django 6.0.4 on 2026-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_profile_profile_image_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.CharField(default="male_1", max_length=50),
        ),
    ]
