# Generated by Django 6.0.4 on 2026-04-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
