# Generated by Django 6.0.4 on 2026-04-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_shopbanner_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopbanner",
            name="link",
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
