# Generated by Django 6.0.4 on 2026-04-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_shopbanner_link_featuredbanner_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="phone",
        ),
        migrations.AddField(
            model_name="otp",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
