# Generated by Django 6.0.4 on 2026-04-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_otp_phone_otp_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
