# Generated by Django 6.0.4 on 2026-04-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_appsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reward_credits",
            field=models.IntegerField(default=0),
        ),
    ]
