# Generated by Django 6.0.4 on 2026-04-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_profile_reward_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.shop",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(default="general", max_length=20),
        ),
    ]
