# Generated by Django 4.2.7 on 2026-05-02 18:36
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_featuredbanner_image_alter_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopbanner',
            name='discount',
            field=models.CharField(max_length=100, null=True, blank=True),
        ),
    ]