# Generated by Django 4.2.7 on 2026-05-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_favorite_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
