# Generated by Django 4.2.7 on 2026-05-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_otp_is_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="shop",
            name="has_quantity_feature",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="FeaturePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[("inventory", "Inventory Feature")], max_length=50
                    ),
                ),
                ("payment_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.shop"
                    ),
                ),
            ],
        ),
    ]
