# Generated by Django 4.2.7 on 2026-05-18 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_item_quantity_shop_has_quantity_feature_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="has_quantity_feature",
        ),
        migrations.DeleteModel(
            name="FeaturePurchase",
        ),
    ]
