# Generated by Django 4.2.7 on 2026-05-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_remove_item_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="track_quantity",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shop",
            name="has_quantity_feature",
            field=models.BooleanField(default=False),
        ),
    ]
