# Generated by Django 4.2.7 on 2026-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_item_quantity_item_track_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
