# Generated by Django 4.2.7 on 2026-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredbanner",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="global_banner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="visibility_radius",
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name="featuredbanner",
            name="background_color",
            field=models.CharField(default="#1B6B50", max_length=20),
        ),
        migrations.AlterField(
            model_name="featuredbanner",
            name="banner_type",
            field=models.CharField(default="image", max_length=20),
        ),
        migrations.AlterField(
            model_name="featuredbanner",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="featured_banners/"
            ),
        ),
        migrations.AlterField(
            model_name="featuredbanner",
            name="small_text",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="featuredbanner",
            name="subtitle",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="featuredbanner",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
