# Generated by Django 4.2.7 on 2026-05-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_featuredbanner_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredbanner",
            name="is_sponsored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="featuredbanner",
            name="priority",
            field=models.IntegerField(default=0),
        ),
    ]
