# Generated by Django 4.2.7 on 2026-05-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_featuredbanner_is_sponsored_featuredbanner_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
