# Generated by Django 4.2.7 on 2026-05-21 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_shop_is_premium"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shop",
            name="is_premium",
        ),
    ]
