# Generated by Django 6.0.4 on 2026-05-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_remove_shop_is_premium"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
