# Generated by Django 6.0.4 on 2026-06-01 09:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_shop_auto_reminder_enabled_credittransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image2",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image2"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="image3",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image3"
            ),
        ),
    ]
