# Generated by Django 4.2.7 on 2026-06-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_item_image2_item_image3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="category",
            field=models.CharField(
                choices=[
                    ("Grocery", "Grocery"),
                    ("Footwear", "Footwear"),
                    ("Fashion", "Fashion"),
                    ("Medicine", "Medicine"),
                    ("Electronics", "Electronics"),
                    ("Bakeries", "Bakeries"),
                    ("Rentals", "Rentals"),
                    ("Stationery", "Stationery"),
                    ("Furniture", "Furniture"),
                    ("Books", "Books"),
                    ("Home & Kitchen", "Home & Kitchen"),
                    ("🔧 Hardware & Tools", "🔧 Hardware & Tools"),
                    ("Computers & Accessories", "Computers & Accessories"),
                    ("🎁 Gifts & Toys", "🎁 Gifts & Toys"),
                    ("Others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
