# Generated by Django 4.2.7 on 2026-06-04 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0040_alter_shop_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ORSApiCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("endpoint", models.CharField(default="directions", max_length=255)),
                ("response_status", models.IntegerField(default=200)),
            ],
            options={
                "verbose_name": "ORS API Calls",
            },
        ),
        migrations.CreateModel(
            name="ActiveUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Active User",
                "verbose_name_plural": "Active Users",
                "unique_together": {("user", "date")},
            },
        ),
    ]
