# Generated by Django 4.2.7 on 2026-06-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_orsapicall_activeuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="referral_reward_claimed",
            field=models.BooleanField(default=False),
        ),
    ]
