# Generated by Django 4.2.7 on 2026-06-10 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_shopview_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_code", models.IntegerField(unique=True)),
                ("version_name", models.CharField(max_length=50)),
                ("release_notes", models.TextField(blank=True)),
                ("is_mandatory", models.BooleanField(default=False)),
                (
                    "notify_users",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True to trigger the update prompt in the app.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "App Release",
                "verbose_name_plural": "App Releases",
                "ordering": ["-version_code"],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="app_version_code",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="app_version_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name="ProPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razorpay_order_id", models.CharField(max_length=100)),
                ("razorpay_payment_id", models.CharField(max_length=100)),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=59.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pro_purchases",
                        to="core.shop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pro Purchase",
                "verbose_name_plural": "Pro Purchases",
                "ordering": ["-created_at"],
            },
        ),
    ]
