# Generated by Django 4.2.7 on 2026-06-10 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0044_apprelease_profile_app_version_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("razorpay_order_id", models.CharField(max_length=100)),
                ("razorpay_payment_id", models.CharField(max_length=100)),
                (
                    "razorpay_signature",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("customer", "Customer App"),
                            ("merchant", "Merchant App"),
                            ("web", "Web Platform"),
                        ],
                        default="customer",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Contribution",
                "verbose_name_plural": "Support Contributions",
                "ordering": ["-created_at"],
            },
        ),
    ]
