# Generated by Django 4.2.7 on 2026-06-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_supportcontribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="last_auto_close",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="last_auto_open",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
