# Generated by Django 4.2.7 on 2026-06-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_shop_last_auto_close_shop_last_auto_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="appsettings",
            name="free_tier_limit",
            field=models.IntegerField(
                default=20, help_text="Base item limit for free tier shops"
            ),
        ),
        migrations.AddField(
            model_name="appsettings",
            name="pro_tier_limit",
            field=models.IntegerField(
                default=120, help_text="Base item limit for pro tier shops"
            ),
        ),
    ]
