# Generated by Django 6.0.4 on 2026-06-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_appsettings_free_tier_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
