# Generated by Django 4.2.7 on 2026-06-12 11:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_alter_shop_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featuredbanner",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
