# Generated by Django 4.2.7 on 2026-06-12 11:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_alter_featuredbanner_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="featuredbanner",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="video"
            ),
        ),
    ]
