# Generated by Django 6.0.4 on 2026-06-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_featuredbanner_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featuredbanner",
            name="video",
        ),
    ]
