# Generated by Django 4.2.7 on 2026-06-14 18:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_shop_delivery_area_shop_delivery_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image4",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image4"
            ),
        ),
    ]
