# Generated by Django 4.2.7 on 2026-06-14 19:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_item_image4"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopbanner",
            name="detail_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="detail_image"
            ),
        ),
    ]
