# Generated by Django 4.2.7 on 2026-06-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_shopbanner_detail_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="delivery_range",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
