# Generated by Django 6.0.4 on 2026-06-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_reset_nondemo_shop_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
