# Generated by Django 6.0.4 on 2026-06-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_shoprating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="delivery_charge",
            field=models.CharField(default="0.0", max_length=255),
        ),
    ]
