# Generated by Django 4.2.7 on 2026-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_alter_shop_delivery_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="COD", max_length=50),
        ),
        migrations.AddField(
            model_name="shop",
            name="cod_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="online_payment_allowed",
            field=models.BooleanField(default=True),
        ),
    ]
