# Generated by Django 4.2.7 on 2026-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_order_payment_method_shop_cod_allowed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="payment_policy",
            field=models.CharField(default="both", max_length=50),
        ),
    ]
